# Generated by Django 6.0.6 on 2026-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mods_files/'),
        ),
    ]
