# Generated by Django 6.0.6 on 2026-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_asset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
    ]
